// migrate.js — run once with: node migrate.js
// Place this in your project root (same folder as package.json)

import mongoose from "mongoose";
import dotenv from "dotenv";
dotenv.config({ path: ".env" });

const MONGODB_URI = process.env.MONGODB_URI;

const img = {
  bluecap:                  "/uploads/products/bluecap.jpg",
  beigecap:                 "/uploads/products/beigecap.jpg",
  beigecap1:                "/uploads/products/beigecap1.jpg",
  beigecap2:                "/uploads/products/beigecap2.jpg",
  beigecap3:                "/uploads/products/beigecap3.jpg",
  bluetie:                  "/uploads/products/bluetie.jpg",
  blackleather1:            "/uploads/products/blackleather1.jpg",
  blackleather2:            "/uploads/products/blackleather2.jpg",
  blackleather3:            "/uploads/products/blackleather3.jpg",
  blackleather4:            "/uploads/products/blackleather4.jpg",
  lunchbox1:                "/uploads/products/lunchbox1.jpg",
  lunchbox2:                "/uploads/products/lunchbox2.jpg",
  lunchbox3:                "/uploads/products/lunchbox3.jpg",
  executive_orange1:        "/uploads/products/executive_orange1.jpg",
  executive_orange2:        "/uploads/products/executive_orange2.jpg",
  executive_orange3:        "/uploads/products/executive_orange3.jpg",
  executive_orange4:        "/uploads/products/executive_orange4.jpg",
  executive_orange5:        "/uploads/products/executive_orange5.jpg",
  executive_orange6:        "/uploads/products/executive_orange6.jpg",
  executive_orange7:        "/uploads/products/executive_orange7.jpg",
  executive_oxblood1:       "/uploads/products/executive_oxblood1.jpg",
  executive_oxblood2:       "/uploads/products/executive_oxblood2.jpg",
  executive_oxblood3:       "/uploads/products/executive_oxblood3.jpg",
  executive_oxblood4:       "/uploads/products/executive_oxblood4.jpg",
  executive_oxblood5:       "/uploads/products/executive_oxblood5.jpg",
  executive_oxblood6:       "/uploads/products/executive_oxblood6.jpg",
  executive_oxblood7:       "/uploads/products/executive_oxblood7.jpg",
  huntergreenleather1:      "/uploads/products/huntergreenleather1.jpg",
  huntergreenleather2:      "/uploads/products/huntergreenleather2.jpg",
  huntergreenleather3:      "/uploads/products/huntergreenleather3.jpg",
  huntergreenleather4:      "/uploads/products/huntergreenleather4.jpg",
  huntergreenleather5:      "/uploads/products/huntergreenleather5.jpg",
  huntergreenleather6:      "/uploads/products/huntergreenleather6.jpg",
  huntergreenleather7:      "/uploads/products/huntergreenleather7.jpg",
  oxbloodleather1:          "/uploads/products/oxbloodleather1.jpg",
  oxbloodleather2:          "/uploads/products/oxbloodleather2.jpg",
  oxbloodleather3:          "/uploads/products/oxbloodleather3.jpg",
  oxbloodleather4:          "/uploads/products/oxbloodleather4.jpg",
  oxbloodleather5:          "/uploads/products/oxbloodleather5.jpg",
  oxbloodleather6:          "/uploads/products/oxbloodleather6.jpg",
  oxbloodleather7:          "/uploads/products/oxbloodleather7.jpg",
  burgundyleather1:         "/uploads/products/burgundyleather1.jpg",
  burgundyleather2:         "/uploads/products/burgundyleather2.jpg",
  burgundyleather3:         "/uploads/products/burgundyleather3.jpg",
  burgundyleather4:         "/uploads/products/burgundyleather4.jpg",
  burgundyleather5:         "/uploads/products/burgundyleather5.jpg",
  burgundyleather6:         "/uploads/products/burgundyleather6.jpg",
  pu_leather_tan1:          "/uploads/products/pu_leather_tan1.jpg",
  pu_leather_tan2:          "/uploads/products/pu_leather_tan2.jpg",
  pu_leather_tan3:          "/uploads/products/pu_leather_tan3.jpg",
  pu_leather_tan4:          "/uploads/products/pu_leather_tan4.jpg",
  pu_leather_tan5:          "/uploads/products/pu_leather_tan5.jpg",
  pu_leather_tan6:          "/uploads/products/pu_leather_tan6.jpg",
  pu_leather_tan7:          "/uploads/products/pu_leather_tan7.jpg",
  royalblueleather1:        "/uploads/products/royalblueleather1.jpg",
  royalblueleather2:        "/uploads/products/royalblueleather2.jpg",
  royalblueleather3:        "/uploads/products/royalblueleather3.jpg",
  royalblueleather4:        "/uploads/products/royalblueleather4.jpg",
  royalblueleather5:        "/uploads/products/royalblueleather5.jpg",
  royalblueleather6:        "/uploads/products/royalblueleather6.jpg",
  royalblueleather7:        "/uploads/products/royalblueleather7.jpg",
  messanger_green1:         "/uploads/products/messanger_green1.jpg",
  messanger_green2:         "/uploads/products/messanger_green2.jpg",
  messanger_green3:         "/uploads/products/messanger_green3.jpg",
  messanger_green4:         "/uploads/products/messanger_green4.jpg",
  messanger_green5:         "/uploads/products/messanger_green5.jpg",
  messanger_green6:         "/uploads/products/messanger_green6.jpg",
  messanger_green7:         "/uploads/products/messanger_green7.jpg",
  messanger_midnightblue1:  "/uploads/products/messanger_midnightblue1.jpg",
  messanger_midnightblue2:  "/uploads/products/messanger_midnightblue2.jpg",
  messanger_midnightblue3:  "/uploads/products/messanger_midnightblue3.jpg",
  messanger_midnightblue4:  "/uploads/products/messanger_midnightblue4.jpg",
  messanger_midnightblue5:  "/uploads/products/messanger_midnightblue5.jpg",
  messanger_midnightblue6:  "/uploads/products/messanger_midnightblue6.jpg",
  messanger_midnightblue7:  "/uploads/products/messanger_midnightblue7.jpg",
  messanger_orange1:        "/uploads/products/messanger_orange1.jpg",
  messanger_orange2:        "/uploads/products/messanger_orange2.jpg",
  messanger_orange3:        "/uploads/products/messanger_orange3.jpg",
  messanger_orange4:        "/uploads/products/messanger_orange4.jpg",
  messanger_orange5:        "/uploads/products/messanger_orange5.jpg",
  messanger_orange6:        "/uploads/products/messanger_orange6.jpg",
  messanger_orange7:        "/uploads/products/messanger_orange7.jpg",
  messanger_tan1:           "/uploads/products/messanger_tan1.jpg",
  messanger_tan2:           "/uploads/products/messanger_tan2.jpg",
  messanger_tan3:           "/uploads/products/messanger_tan3.jpg",
  messanger_tan4:           "/uploads/products/messanger_tan4.jpg",
  messanger_tan5:           "/uploads/products/messanger_tan5.jpg",
  messanger_tan6:           "/uploads/products/messanger_tan6.jpg",
  messanger_tan7:           "/uploads/products/messanger_tan7.jpg",
  AC_panasonic1:            "/uploads/products/AC_panasonic1.png",
  AC_panasonic2:            "/uploads/products/AC_panasonic2.png",
  AC_panasonic3:            "/uploads/products/AC_panasonic3.png",
  AC_panasonic4:            "/uploads/products/AC_panasonic4.jpg",
  AC_panasonic5:            "/uploads/products/AC_panasonic5.png",
  gift4in1_1:               "/uploads/products/4in1_1.png",
  gift4in1_2:               "/uploads/products/4in1_2.png",
  gift4in1_3:               "/uploads/products/4in1_3.png",
  gift4in1_4:               "/uploads/products/4in1_4.png",
  gift4in1_5:               "/uploads/products/4in1_5.png",
  desk_organizer1:          "/uploads/products/desk_organizer1.png",
  desk_organizer2:          "/uploads/products/desk_organizer2.png",
  desk_organizer3:          "/uploads/products/desk_organizer3.png",
  desk_organizer4:          "/uploads/products/desk_organizer4.png",
  desk_organizer5:          "/uploads/products/desk_organizer5.png",
  fridge_samsung1:          "/uploads/products/fridge_samsung1.png",
  fridge_samsung2:          "/uploads/products/fridge_samsung2.png",
  fridge_samsung3:          "/uploads/products/fridge_samsung3.png",
  fridge_samsung4:          "/uploads/products/fridge_samsung4.png",
  fridge_samsung5:          "/uploads/products/fridge_samsung5.png",
  fridge_samsung6:          "/uploads/products/fridge_samsung6.png",
  premium_pen1:             "/uploads/products/premium_pen1.png",
  premium_pen2:             "/uploads/products/premium_pen2.png",
  premium_pen3:             "/uploads/products/premium_pen3.png",
  metal_trophy1:            "/uploads/products/metal_trophy1.png",
  metal_trophy2:            "/uploads/products/metal_trophy2.png",
  metal_trophy3:            "/uploads/products/metal_trophy3.png",
  metal_trophy4:            "/uploads/products/metal_trophy4.png",
  star_trophy1:             "/uploads/products/star_trophy1.png",
  star_trophy2:             "/uploads/products/star_trophy2.png",
  star_trophy3:             "/uploads/products/star_trophy3.png",
  star_trophy4:             "/uploads/products/star_trophy4.png",
  star_trophy5:             "/uploads/products/star_trophy5.png",
  star_trophy6:             "/uploads/products/star_trophy6.png",
  star_trophy7:             "/uploads/products/star_trophy7.png",
  boat_headphones1:         "/uploads/products/boat_headphones1.png",
  boat_headphones2:         "/uploads/products/boat_headphones2.png",
  boat_headphones3:         "/uploads/products/boat_headphones3.png",
  boat_headphones4:         "/uploads/products/boat_headphones4.png",
  boat_headphones5:         "/uploads/products/boat_headphones5.png",
  induction_prestige1:      "/uploads/products/induction_prestige1.png",
  induction_prestige2:      "/uploads/products/induction_prestige2.png",
  induction_prestige3:      "/uploads/products/induction_prestige3.png",
  induction_prestige4:      "/uploads/products/induction_prestige4.png",
  induction_prestige5:      "/uploads/products/induction_prestige5.png",
  stanely1:                 "/uploads/products/stanely1.png",
  stanely2:                 "/uploads/products/stanely2.png",
  stanely3:                 "/uploads/products/stanely3.png",
  stanely4:                 "/uploads/products/stanely4.png",
  stanely5:                 "/uploads/products/stanely5.png",
  mug1:                     "/uploads/products/mug1.png",
  mug2:                     "/uploads/products/mug2.png",
  mug3:                     "/uploads/products/mug3.png",
  mug4:                     "/uploads/products/mug4.png",
  mug5:                     "/uploads/products/mug5.png",
  gifts3in1_1:              "/uploads/products/gifts3in1_1.png",
  gifts3in1_2:              "/uploads/products/gifts3in1_2.png",
  gifts3in1_3:              "/uploads/products/gifts3in1_3.png",
  gifts3in1_4:              "/uploads/products/gifts3in1_4.png",
  gifts3in1_5:              "/uploads/products/gifts3in1_5.png",
  giftset1:                 "/uploads/products/giftset1.jpeg",
  giftset2:                 "/uploads/products/giftset2.jpeg",
  giftset3:                 "/uploads/products/giftset3.jpeg",
};

const products = [
  { name: "Blue Cap", description: "Stay comfortable and stylish with this versatile cotton baseball cap. Made from high-quality fabric, it provides sun protection while ensuring breathability, making it a practical accessory for any season.", price: 429.99, offerPrice: 329.99, category: "Cap", inStock: true, images: [img.bluecap] },
  { name: "Beige Cap", description: "Stay comfortable and stylish with this versatile cotton baseball cap. Made from high-quality fabric, it provides sun protection while ensuring breathability, making it a practical accessory for any season.", price: 429.99, offerPrice: 329.99, category: "Cap", inStock: true, images: [img.beigecap, img.beigecap1, img.beigecap2, img.beigecap3] },
  { name: "Crocodile RoyalBlue Leather Bag", description: "Elevate your style with the Crocodile-Texture Executive Leather Messenger Bag — a bold, professional statement piece crafted for durability and sophistication.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.royalblueleather1, img.royalblueleather2, img.royalblueleather3, img.royalblueleather4, img.royalblueleather5, img.royalblueleather6, img.royalblueleather7] },
  { name: "PU Leather Tan Bag", description: "Designed for the modern professional, the adjustable shoulder strap ensures comfort, while the structured body keeps its shape even when packed.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.pu_leather_tan1, img.pu_leather_tan2, img.pu_leather_tan3, img.pu_leather_tan4, img.pu_leather_tan5, img.pu_leather_tan6, img.pu_leather_tan7] },
  { name: "Crocodile Burgundy Leather Bag", description: "Step up your style with the UZR Croc-Textured Black Leather Messenger Bag — a refined blend of luxury design and daily practicality.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.burgundyleather1, img.burgundyleather2, img.burgundyleather3, img.burgundyleather4, img.burgundyleather5, img.burgundyleather6] },
  { name: "Crocodile OxBlood Bag", description: "Elevate your style with the Crocodile-Texture Executive Leather Messenger Bag — a bold, professional statement piece crafted for durability and sophistication.", price: 899.99, offerPrice: 799.99, category: "Bags", inStock: true, images: [img.oxbloodleather1, img.oxbloodleather2, img.oxbloodleather3, img.oxbloodleather4, img.oxbloodleather5, img.oxbloodleather6, img.oxbloodleather7] },
  { name: "Crocodile Hunter Green Bag", description: "Elevate your style with the Crocodile-Texture Executive Leather Messenger Bag — a bold, professional statement piece crafted for durability and sophistication.", price: 899.99, offerPrice: 799.99, category: "Bags", inStock: true, images: [img.huntergreenleather1, img.huntergreenleather2, img.huntergreenleather3, img.huntergreenleather4, img.huntergreenleather5, img.huntergreenleather6, img.huntergreenleather7] },
  { name: "Executive Leather Bag (Orange)", description: "Crafted from premium-grade genuine leather, the UZR Executive Office Bag is built for the modern professional.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.executive_orange1, img.executive_orange2, img.executive_orange3, img.executive_orange4, img.executive_orange5, img.executive_orange6, img.executive_orange7] },
  { name: "Executive Leather Bag (Oxblood)", description: "Crafted from premium-grade genuine leather, the UZR Executive Office Bag is built for the modern professional.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.executive_oxblood1, img.executive_oxblood2, img.executive_oxblood3, img.executive_oxblood4, img.executive_oxblood5, img.executive_oxblood6, img.executive_oxblood7] },
  { name: "Crocodile Black Leather Bag", description: "Elevate your style with the Crocodile-Texture Executive Leather Messenger Bag — a bold, professional statement piece crafted for durability and sophistication.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.blackleather1, img.blackleather2, img.blackleather3, img.blackleather4] },
  { name: "Messanger Green Bag", description: "Upgrade your professional look with the UZR Classic Executive Leather Office Bag — a perfect blend of style, functionality, and premium craftsmanship.", price: 2899.99, offerPrice: 2499.99, category: "Bags", inStock: true, images: [img.messanger_green1, img.messanger_green2, img.messanger_green3, img.messanger_green4, img.messanger_green5, img.messanger_green6, img.messanger_green7] },
  { name: "Messanger MidnightBlue Bag", description: "Upgrade your professional look with the UZR Classic Executive Leather Office Bag — a perfect blend of style, functionality, and premium craftsmanship.", price: 3000.00, offerPrice: 2500.00, category: "Bags", inStock: true, images: [img.messanger_midnightblue1, img.messanger_midnightblue2, img.messanger_midnightblue3, img.messanger_midnightblue4, img.messanger_midnightblue5, img.messanger_midnightblue6, img.messanger_midnightblue7] },
  { name: "Messanger Tan Bag", description: "Upgrade your professional look with the UZR Classic Executive Leather Office Bag — a perfect blend of style, functionality, and premium craftsmanship.", price: 3000.00, offerPrice: 2500.00, category: "Bags", inStock: true, images: [img.messanger_tan1, img.messanger_tan2, img.messanger_tan3, img.messanger_tan4, img.messanger_tan5, img.messanger_tan6, img.messanger_tan7] },
  { name: "Messanger Dark Orange Bag", description: "Upgrade your professional look with the UZR Classic Executive Leather Office Bag — a perfect blend of style, functionality, and premium craftsmanship.", price: 3000.00, offerPrice: 2500.00, category: "Bags", inStock: true, images: [img.messanger_orange1, img.messanger_orange2, img.messanger_orange3, img.messanger_orange4, img.messanger_orange5, img.messanger_orange6, img.messanger_orange7] },
  { name: "Lunch Box", description: "Make mealtime convenient and organized with this complete lunch set. Features a sturdy 750ml aqua bottle, three round containers, and stainless steel spoon and fork.", price: 899.99, offerPrice: 799.99, category: "Gift-Items", inStock: true, images: [img.lunchbox1, img.lunchbox2, img.lunchbox3] },
  { name: "Blue Tie", description: "The Blue Tie adds a touch of sophistication and class to any outfit. Made from high-quality silk blend fabric with a smooth texture and subtle sheen.", price: 399.99, offerPrice: 349.99, category: "Gift-Items", inStock: true, images: [img.bluetie] },
  { name: "Air Conditioner", description: "2 Ton Capacity: Perfect for medium-sized rooms up to 180-230 sq. ft. 100% Copper Condenser for better heat exchange and enhanced durability.", price: 60000.00, offerPrice: 50000.00, category: "Electronics", inStock: true, images: [img.AC_panasonic1, img.AC_panasonic2, img.AC_panasonic3, img.AC_panasonic4, img.AC_panasonic5] },
  { name: "Executive 4 in 1 Gift Set", description: "Premium corporate combo — sleek black wallet, stylish metal pen, classy keychain, and smart card holder, neatly packed in a luxury box.", price: 500.00, offerPrice: 350.00, category: "Gift-Items", inStock: true, images: [img.gift4in1_1, img.gift4in1_2, img.gift4in1_3, img.gift4in1_4, img.gift4in1_5] },
  { name: "Desk Organizer", description: "Keep your workspace tidy with this stylish Desk Organizer. Multiple compartments for pens, markers, notepads, and business cards.", price: 899.99, offerPrice: 799.99, category: "Gift-Items", inStock: true, images: [img.desk_organizer1, img.desk_organizer2, img.desk_organizer3, img.desk_organizer4, img.desk_organizer5] },
  { name: "Refrigerator", description: "Frost Free Refrigerator with Auto Defrost, powerful cooling, and long lasting freshness. 236L capacity. 3 Star Energy Rating.", price: 35499.99, offerPrice: 22499.99, category: "Electronics", inStock: true, images: [img.fridge_samsung1, img.fridge_samsung2, img.fridge_samsung3, img.fridge_samsung4, img.fridge_samsung5, img.fridge_samsung6] },
  { name: "Premium Pen Set", description: "Stylish wooden pen set featuring two elegant pens encased in a smooth wooden box. Ideal for corporate gifts and awards.", price: 250.00, offerPrice: 120.00, category: "Gift-Items", inStock: true, images: [img.premium_pen1, img.premium_pen2, img.premium_pen3] },
  { name: "Metal Trophy", description: "Honor exceptional talent with this beautifully designed Excellence Award Plaque. High-quality wood with a lustrous metallic engraving plate.", price: 899.99, offerPrice: 799.99, category: "Trophy", inStock: true, images: [img.metal_trophy1, img.metal_trophy2, img.metal_trophy3, img.metal_trophy4] },
  { name: "Star Trophy", description: "Celebrate excellence with this beautifully crafted Star Achiever Award. Contemporary gold-tone finish with an eye-catching star motif.", price: 600.00, offerPrice: 400.00, category: "Trophy", inStock: true, images: [img.star_trophy1, img.star_trophy2, img.star_trophy3, img.star_trophy4, img.star_trophy5, img.star_trophy6, img.star_trophy7] },
  { name: "Boat Headphone", description: "40 hours of Playback with boAt Rockerz 421 Bluetooth Headphones. 40mm drivers with boAt Signature Sound for bass-heavy audio.", price: 1699.99, offerPrice: 1399.99, category: "Electronics", inStock: true, images: [img.boat_headphones1, img.boat_headphones2, img.boat_headphones3, img.boat_headphones4, img.boat_headphones5] },
  { name: "Induction Cooktop", description: "Prestige Atlas Touch Induction Cooktop. 2000W, 230V. Sleek black glass worktop with advanced induction technology.", price: 2899.99, offerPrice: 2499.99, category: "Electronics", inStock: true, images: [img.induction_prestige1, img.induction_prestige2, img.induction_prestige3, img.induction_prestige4, img.induction_prestige5] },
  { name: "Milton Mug", description: "Vacuum insulated Mug in 304 stainless steel with inner copper coating. Keeps beverages hot or cold for hours.", price: 600.00, offerPrice: 800.00, category: "Bottles", inStock: true, images: [img.mug1, img.mug2, img.mug3, img.mug4, img.mug5] },
  { name: "Stanley Tumbler", description: "H2.0 FlowState tumbler with double wall vacuum insulation. Drinks stay cold, iced or hot for hours. Fits most car cup holders.", price: 300.00, offerPrice: 500.00, category: "Bottles", inStock: true, images: [img.stanely1, img.stanely2, img.stanely3, img.stanely4, img.stanely5] },
  { name: "Gift Set 3 in 1", description: "Well-matched Corporate Set of 3 — A5 diary, pen, and accessories. Ideal for internal distribution, seasonal recognition, or onboarding.", price: 2000.00, offerPrice: 1500.00, category: "Gift-Items", inStock: true, images: [img.gifts3in1_1, img.gifts3in1_2, img.gifts3in1_3, img.gifts3in1_4, img.gifts3in1_5] },
  { name: "Blue 4 in 1 Gift Set", description: "Premium Executive Gift Set — Notebook, Pen & Keychain beautifully packed in a luxury gift box. Perfect for corporate gifting.", price: 1800.00, offerPrice: 1300.00, category: "Gift-Items", inStock: true, images: [img.giftset1] },
  { name: "White 4 in 1 Gift Set", description: "Premium Executive Gift Set — Notebook, Pen & Keychain beautifully packed in a luxury gift box. Perfect for corporate gifting.", price: 1800.00, offerPrice: 1300.00, category: "Gift-Items", inStock: true, images: [img.giftset2] },
  { name: "Greenish 3 in 1 Gift Set", description: "Premium Executive Gift Set — Notebook, Pen & Keychain beautifully packed in a luxury gift box. Perfect for corporate gifting.", price: 1800.00, offerPrice: 1000.00, category: "Gift-Items", inStock: true, images: [img.giftset3] },
];

const ProductSchema = new mongoose.Schema(
  { name: { type: String, required: true }, description: { type: String, required: true }, price: { type: Number, required: true }, offerPrice: { type: Number }, category: { type: String, required: true }, images: [{ type: String }], inStock: { type: Boolean, default: true } },
  { timestamps: true }
);

const Product = mongoose.models?.Product || mongoose.model("Product", ProductSchema);

async function migrate() {
  console.log("Connecting to MongoDB...");
  await mongoose.connect(MONGODB_URI);
  console.log("Connected!");
  await Product.deleteMany({});
  console.log("Cleared existing products.");
  const inserted = await Product.insertMany(products);
  console.log("✅ Done! Inserted " + inserted.length + " products into MongoDB.");
  await mongoose.disconnect();
  console.log("You can now delete migrate.js");
}

migrate().catch((err) => {
  console.error("❌ Migration failed:", err.message);
  process.exit(1);
});